### ISSUE TITLE
Just a question - how did you managed automatic DB initialization?

### ISSUE THREAD

**Issue by lamanawebu** [stackmanoj/chatapp#2]
Hi Manoj :-)
thx for very useful example, probably the best one for signal with DB and UI.
I am wondering where or how is automatic DB initialization set or started.
Thank you for hint or link.
Tom

**Comment by stackmanoj** [comment]
Hi,

I am using entity framework as ORM. So entity framework itself doing
database initialization when not found tables that we have used in code.

Thanks

**Comment by nguyendn11** [comment]
Hi friend , i can't chat with ur application . Alaway got no friend online when open 2 tabs . What wrong with it :(

**Comment by stackmanoj** [comment]
Hi
In same browser you can not login with multiple users.
You have to login in multiple browsers for chating.
And you have to send friend request and after acceptance  from friends side
you can chat.

Thanks

**Comment by nguyendn11** [comment]
Hi bro , thank you for replying me . 
I knew ur idea, i open 2 diffrenent broswer , IE and Chrome . 
Logged in 2 different account , but can't see where is the friend request . 
Can you help me a little . Thanks
![image](https://user-images.githubusercontent.com/39287728/51885239-3ff01300-23bd-11e9-9ae8-7cdd7fa9ac72.png)

**Comment by stackmanoj** [comment]
Hi
Search another friends name and send Friend request

**Comment by nguyendn11** [comment]
Thank u , success

**Comment by alexandrunguta** [comment]
Hi,
I targeted in web.config an empty database, but when i try to login/sign up the application throws me System.Data.ProviderIncompatibleException: 'An error occurred while getting provider information from the database. This can be caused by Entity Framework using an incorrect connection string. Check the inner exceptions for details and ensure that the connection string is correct.'

So, the application doesn't create or see the database.
Can you help me, please ?
![1](https://user-images.githubusercontent.com/24647512/54870362-2c09d180-4dae-11e9-91e5-d57406929f27.PNG)
![2](https://user-images.githubusercontent.com/24647512/54870368-48a60980-4dae-11e9-9e31-fbba823cdc7b.PNG)

**Comment by stackmanoj** [comment]
Hi,
Set your connection string as I did in demo.
Your connection string in screenshot is looking fine

**Comment by Tuglo** [comment]
HELLO CANT LOGIN AND CANT REGISTER
